2022-03-27 03:23:19,595 INFO    MainThread:988 [wandb_setup.py:_flush():75] Loading settings from C:\Users\rohit\.config\wandb\settings
2022-03-27 03:23:19,595 INFO    MainThread:988 [wandb_setup.py:_flush():75] Loading settings from C:\Users\rohit\Personal Projects\Traffic Lights Genetic Algorithm\wandb\settings
2022-03-27 03:23:19,595 INFO    MainThread:988 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-27 03:23:19,596 INFO    MainThread:988 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-27 03:23:19,596 INFO    MainThread:988 [wandb_init.py:_log_setup():405] Logging user logs to C:\Users\rohit\Personal Projects\Traffic Lights Genetic Algorithm\wandb\run-20220327_032319-tw8qb255\logs\debug.log
2022-03-27 03:23:19,597 INFO    MainThread:988 [wandb_init.py:_log_setup():406] Logging internal logs to C:\Users\rohit\Personal Projects\Traffic Lights Genetic Algorithm\wandb\run-20220327_032319-tw8qb255\logs\debug-internal.log
2022-03-27 03:23:19,597 INFO    MainThread:988 [wandb_init.py:init():439] calling init triggers
2022-03-27 03:23:19,597 INFO    MainThread:988 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'config_file': 'Manhattan5x3.sumocfg', 'collision_penalty': 400, 'waiting_time_weight': 0.0005, 'emissions_weight': 0.0005, 'architecture': 'Genetic Algorithm', 'population_size': 15, 'max_generations': 100, 'n_survivors': 3, 'crossover_rate': 0.5, 'duration_mutation_rate': 0.2, 'duration_mutation_strength': 5, 'states_mutation_rate': 0.2}
2022-03-27 03:23:19,597 INFO    MainThread:988 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3nu7ayek
2022-03-27 03:23:19,599 INFO    MainThread:988 [wandb_run.py:finish():1539] finishing run dharma/Manhattan 5x3 Genetic Algorithm/3nu7ayek
2022-03-27 03:23:19,600 INFO    MainThread:988 [jupyter.py:save_history():429] not saving jupyter history
2022-03-27 03:23:19,600 INFO    MainThread:988 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-27 03:23:19,600 INFO    MainThread:988 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-27 03:23:19,600 INFO    MainThread:988 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-27 03:23:19,601 INFO    MainThread:988 [wandb_run.py:_restore():1674] restore
2022-03-27 03:23:20,603 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 728
}

2022-03-27 03:23:20,724 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 728
}

2022-03-27 03:23:20,921 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 728
}

2022-03-27 03:23:21,444 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 3920
}

2022-03-27 03:23:21,554 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 3946
}

2022-03-27 03:23:21,665 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 3946
}

2022-03-27 03:23:21,774 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:21,885 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:21,994 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:22,098 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:22,209 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:22,487 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}

2022-03-27 03:23:22,967 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3946
  total_bytes: 3946
}
local_info {
}

2022-03-27 03:23:24,099 INFO    MainThread:988 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-27 03:23:24,100 INFO    MainThread:988 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-27 03:23:24,102 INFO    MainThread:988 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-27 03:23:24,106 INFO    MainThread:988 [wandb_init.py:init():492] starting backend
2022-03-27 03:23:24,106 INFO    MainThread:988 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-27 03:23:24,113 INFO    MainThread:988 [backend.py:ensure_launched():219] starting backend process...
2022-03-27 03:23:24,191 INFO    MainThread:988 [backend.py:ensure_launched():224] started backend process with pid: 10740
2022-03-27 03:23:24,191 INFO    MainThread:988 [wandb_init.py:init():501] backend started and connected
2022-03-27 03:23:24,210 INFO    MainThread:988 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-27 03:23:24,210 INFO    MainThread:988 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'charmap' codec can't decode byte 0x90 in position 8560: character maps to <undefined>
2022-03-27 03:23:24,210 INFO    MainThread:988 [wandb_init.py:init():565] updated telemetry
2022-03-27 03:23:24,211 INFO    MainThread:988 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-27 03:23:25,847 INFO    MainThread:988 [wandb_run.py:_on_init():1759] communicating current version
2022-03-27 03:23:25,933 INFO    MainThread:988 [wandb_run.py:_on_init():1763] got version response 
2022-03-27 03:23:25,934 INFO    MainThread:988 [wandb_init.py:init():625] starting run threads in backend
2022-03-27 03:23:25,980 INFO    MainThread:988 [wandb_run.py:_console_start():1733] atexit reg
2022-03-27 03:23:25,981 INFO    MainThread:988 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-27 03:23:25,981 INFO    MainThread:988 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-27 03:23:25,983 INFO    MainThread:988 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-27 03:23:25,983 INFO    MainThread:988 [wandb_init.py:init():664] run started, returning control to user process
2022-03-27 03:36:34,448 INFO    MainThread:988 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-27 03:36:34,449 INFO    MainThread:988 [wandb_run.py:_restore():1674] restore
2022-03-27 03:36:34,969 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 728
}

2022-03-27 03:36:35,707 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 6214
}

2022-03-27 03:36:35,821 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 6498
}

2022-03-27 03:36:35,930 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 728
  total_bytes: 6498
}

2022-03-27 03:36:36,040 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

2022-03-27 03:36:36,151 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

2022-03-27 03:36:36,259 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

2022-03-27 03:36:36,365 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

2022-03-27 03:36:36,475 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

2022-03-27 03:36:36,979 INFO    MainThread:988 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6498
  total_bytes: 6498
}

